Phyu_ShunLei_Weekly Assignment 1_Q11

In [2]:
# Import required packages
import pandas as pd
 # Load data
toyotacorolla_df = pd.read_csv('ToyotaCorolla.csv')
print(toyotacorolla_df)  # show all the data

        Id                                              Model  Price  \
0        1      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13500
1        2      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13750
2        3     ?TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13950
3        4      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  14950
4        5        TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  13750
...    ...                                                ...    ...
1431  1438         TOYOTA Corolla 1.3 16V HATCHB G6 2/3-Doors   7500
1432  1439  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...  10845
1433  1440  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...   8500
1434  1441  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...   7250
1435  1442        TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors   6950

      Age_08_04  Mfg_Month  Mfg_Year     KM Fuel_Type   HP  Met_Color  ...  \
0            23         10      2002  46986    Diesel   90          1  ...
1            23         10      2002  72937    Diesel   90          1  ...
2            24          9      2002  41711    Diesel   90          1  ...
3            26          7      2002  48000    Diesel   90          0  ...
4            30          3      2002  38500    Diesel   90          0  ...
...         ...        ...       ...    ...       ...  ...        ...  ...
1431         69         12      1998  20544    Petrol   86          1  ...
1432         72          9      1998  19000    Petrol   86          0  ...
1433         71         10      1998  17016    Petrol   86          0  ...
1434         70         11      1998  16916    Petrol   86          1  ...
1435         76          5      1998      1    Petrol  110          0  ...

      Central_Lock  Powered_Windows  Power_Steering  Radio  Mistlamps  \
0                1                1               1      0          0
1                1                0               1      0          0
2                0                0               1      0          0
3                0                0               1      0          0
4                1                1               1      0          1
...            ...              ...             ...    ...        ...
1431             1                1               1      0          1
1432             0                0               1      0          0
1433             0                0               1      0          0
1434             0                0               0      0          0
1435             0                0               1      0          0

      Sport_Model  Backseat_Divider  Metallic_Rim  Radio_cassette  Tow_Bar
0               0                 1             0               0        0
1               0                 1             0               0        0
2               0                 1             0               0        0
3               0                 1             0               0        0
4               0                 1             0               0        0
...           ...               ...           ...             ...      ...
1431            1                 1             0               0        0
1432            1                 1             0               0        0
1433            0                 1             0               0        0
1434            0                 1             0               0        0
1435            0                 0             0               0        0

[1436 rows x 37 columns]

In [3]:
# Check for missing values
print(toyotacorolla_df.isnull().sum())  # Summarize missing values by column

Id                  0
Model               0
Price               0
Age_08_04           0
Mfg_Month           0
Mfg_Year            0
KM                  0
Fuel_Type           0
HP                  0
Met_Color           0
Automatic           0
cc                  0
Doors               0
Cylinders           0
Gears               0
Quarterly_Tax       0
Weight              0
Mfr_Guarantee       0
BOVAG_Guarantee     0
Guarantee_Period    0
ABS                 0
Airbag_1            0
Airbag_2            0
Airco               0
Automatic_airco     0
Boardcomputer       0
CD_Player           0
Central_Lock        0
Powered_Windows     0
Power_Steering      0
Radio               0
Mistlamps           0
Sport_Model         0
Backseat_Divider    0
Metallic_Rim        0
Radio_cassette      0
Tow_Bar             0
dtype: int64

In [5]:
# use drop_first=True to drop the first dummy variable
toyotacorolla_df_df = pd.get_dummies(toyotacorolla_df, prefix_sep='_',drop_first=True)
toyotacorolla_df.columns
toyotacorolla_df.loc[:, 'Fuel_Type':'Met_Color']

     Fuel_Type   HP  Met_Color
0       Diesel   90          1
1       Diesel   90          1
2       Diesel   90          1
3       Diesel   90          0
4       Diesel   90          0
...        ...  ...        ...
1431    Petrol   86          1
1432    Petrol   86          0
1433    Petrol   86          0
1434    Petrol   86          1
1435    Petrol  110          0

[1436 rows x 3 columns]

In [7]:
# Convert 'Fuel_Type' and 'Met_Color' to dummy variables
# Note: Changed column names to match likely column names in the dataframe
toyotacorolla_df_dummies = pd.get_dummies(toyotacorolla_df, columns=["Fuel_Type", "Met_Color"], drop_first=True)

# Display the first few rows of the transformed dataset
print(toyotacorolla_df_dummies.head())

   Id                                           Model  Price  Age_08_04  \
0   1   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13500         23
1   2   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13750         23
2   3  ?TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13950         24
3   4   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  14950         26
4   5     TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  13750         30

   Mfg_Month  Mfg_Year     KM  HP  Automatic    cc  ...  Radio  Mistlamps  \
0         10      2002  46986  90          0  2000  ...      0          0
1         10      2002  72937  90          0  2000  ...      0          0
2          9      2002  41711  90          0  2000  ...      0          0
3          7      2002  48000  90          0  2000  ...      0          0
4          3      2002  38500  90          0  2000  ...      0          1

   Sport_Model  Backseat_Divider  Metallic_Rim  Radio_cassette  Tow_Bar  \
0            0                 1             0               0        0
1            0                 1             0               0        0
2            0                 1             0               0        0
3            0                 1             0               0        0
4            0                 1             0               0        0

   Fuel_Type_Diesel  Fuel_Type_Petrol  Met_Color_1
0              True             False         True
1              True             False         True
2              True             False         True
3              True             False        False
4              True             False        False

[5 rows x 38 columns]

In [10]:

from sklearn.model_selection import train_test_split
# random_state is set to a defined value to get the same partitions when re-running the code

# First split: 60% training, 40% validation
trainData, validData = train_test_split(toyotacorolla_df, test_size=0.40, random_state=1)
print('Training : ', trainData.shape)
print('Validation : ', validData.shape)
print()

# split: 50% training, 30% validation, 20% test
trainData, temp = train_test_split(toyotacorolla_df, test_size=0.5, random_state=1)
validData, testData = train_test_split(temp, test_size=0.4, random_state=1)
print('Training   : ', trainData.shape)
print('Validation : ', validData.shape)
print('Test       : ', testData.shape)

Training :  (861, 37)
Validation :  (575, 37)

Training   :  (718, 37)
Validation :  (430, 37)
Test       :  (288, 37)